/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as NewRouteImport } from './routes/new'
import { Route as DryRunRouteImport } from './routes/dry-run'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVoiceTurnRouteImport } from './routes/api/public/voice-turn'
import { Route as ApiPublicTwimlRouteImport } from './routes/api/public/twiml'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DryRunRoute = DryRunRouteImport.update({
  id: '/dry-run',
  path: '/dry-run',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceTurnRoute = ApiPublicVoiceTurnRouteImport.update({
  id: '/api/public/voice-turn',
  path: '/api/public/voice-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwimlRoute = ApiPublicTwimlRouteImport.update({
  id: '/api/public/twiml',
  path: '/api/public/twiml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/dry-run': typeof DryRunRoute
  '/new': typeof NewRoute
  '/quotes': typeof QuotesRoute
  '/report': typeof ReportRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/twiml': typeof ApiPublicTwimlRoute
  '/api/public/voice-turn': typeof ApiPublicVoiceTurnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/dry-run': typeof DryRunRoute
  '/new': typeof NewRoute
  '/quotes': typeof QuotesRoute
  '/report': typeof ReportRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/twiml': typeof ApiPublicTwimlRoute
  '/api/public/voice-turn': typeof ApiPublicVoiceTurnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/dry-run': typeof DryRunRoute
  '/new': typeof NewRoute
  '/quotes': typeof QuotesRoute
  '/report': typeof ReportRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/twiml': typeof ApiPublicTwimlRoute
  '/api/public/voice-turn': typeof ApiPublicVoiceTurnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calls'
    | '/dry-run'
    | '/new'
    | '/quotes'
    | '/report'
    | '/api/public/tts'
    | '/api/public/twiml'
    | '/api/public/voice-turn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calls'
    | '/dry-run'
    | '/new'
    | '/quotes'
    | '/report'
    | '/api/public/tts'
    | '/api/public/twiml'
    | '/api/public/voice-turn'
  id:
    | '__root__'
    | '/'
    | '/calls'
    | '/dry-run'
    | '/new'
    | '/quotes'
    | '/report'
    | '/api/public/tts'
    | '/api/public/twiml'
    | '/api/public/voice-turn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  DryRunRoute: typeof DryRunRoute
  NewRoute: typeof NewRoute
  QuotesRoute: typeof QuotesRoute
  ReportRoute: typeof ReportRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicTwimlRoute: typeof ApiPublicTwimlRoute
  ApiPublicVoiceTurnRoute: typeof ApiPublicVoiceTurnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dry-run': {
      id: '/dry-run'
      path: '/dry-run'
      fullPath: '/dry-run'
      preLoaderRoute: typeof DryRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-turn': {
      id: '/api/public/voice-turn'
      path: '/api/public/voice-turn'
      fullPath: '/api/public/voice-turn'
      preLoaderRoute: typeof ApiPublicVoiceTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twiml': {
      id: '/api/public/twiml'
      path: '/api/public/twiml'
      fullPath: '/api/public/twiml'
      preLoaderRoute: typeof ApiPublicTwimlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  DryRunRoute: DryRunRoute,
  NewRoute: NewRoute,
  QuotesRoute: QuotesRoute,
  ReportRoute: ReportRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicTwimlRoute: ApiPublicTwimlRoute,
  ApiPublicVoiceTurnRoute: ApiPublicVoiceTurnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
